flowchart LR
  ADM([Administrador])

  subgraph Auditoría
    UA1(Consultar auditoría de pacientes)
    UA2(Consultar auditoría de antecedentes)
    UA3(Consultar auditoría de citas)
    UA4(Consultar auditoría de insumos)
    UA5(Consultar auditoría de donantes)
    UA6(Consultar auditoría de donaciones)
    UA7(Consultar auditoría de asientos contables)
    UA8(Consultar accesos a consultas contables)
  end

  ADM --> UA1 & UA2 & UA3 & UA4 & UA5 & UA6 & UA7 & UA8