flowchart LR
  P([Personal])

  subgraph Donaciones
    UC20(Registrar donante)
    UC21(Consultar donantes)
    UC22(Registrar donación)
    UC23(Consultar donaciones)
    UC24(Asociar insumos a donación)
  end

  P --> UC20 & UC21 & UC22 & UC23 & UC24
  UC22 -.->|include| UC24
  UC22 -.->|extend| UC_ingreso(Registrar asiento de ingreso)
  UC24 -.->|include| UC12