flowchart LR
    NA([Usuario no autenticado])
    ADM([Administrador])
    P([Personal])

    subgraph Auth
        UC_login(Iniciar sesión)
        UC_logout(Cerrar sesión)
        UC_recover(Recuperar contraseña)
        UC_register(Registrar personal)
        UC_edit_staff(Editar personal)
        UC_deactivate(Desactivar personal)
    end

    NA --> UC_login
    NA --> UC_recover
    P  --> UC_logout
    ADM --> UC_register
    ADM --> UC_edit_staff
    ADM --> UC_deactivate